server:
  port: 9527
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-eureka-server7001
          uri: http://localhost:7001
          predicates:
            - Path=/eureka/**
        - id: cloud-provider-payment
          uri: lb://cloud-provider-payment
          predicates:
            - Path=/payment/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka